spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KINDE_ISSUER_URI}
          jwk-set-uri: ${KINDE_JWK_SET_URI}

management:
  endpoints:
    web:
      exposure:
        include:
          - health